version: '3'

services:

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=dev
    volumes:
      - ./mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8200:8081"
    depends_on:
      - mongodb
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=dev
      - ME_CONFIG_MONGODB_ADMINPASSWORD=dev
      - ME_CONFIG_MONGODB_SERVER=mongodb

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    restart: unless-stopped
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    volumes:
      - ./Biblioteca:/app/Biblioteca
